language: node_js
node_js:
  - '12'

services:
  - docker

before_install:
  - npm install yarn && yarn install && yarn build && (cd packages/omg; yarn link)

script:
  - cd tests/regression && ./travis.sh
