version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: yarn-install
          command: yarn
      - run:
          name: eslint
          command: yarn workspace omg-cli eslint
      - run:
          name: test-with-coverage
          command: yarn workspace omg-cli coverage
      - run:
          name: upload-to-codecov
          command: bash <(curl -s https://codecov.io/bash)
