version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.7
    steps:
      - checkout
      - run:
          name: get-yarn
          command: 'sudo apt-get update && sudo apt-get install yarn'
      - run:
          name: get-the-deps
          command: yarn install
      - run:
          name: test
          command: npm test
